/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LabRouteImport } from './routes/lab'
import { Route as CropsSlugRouteImport } from './routes/crops.$slug'

const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsSlugRoute = CropsSlugRouteImport.update({
  id: '/crops/$slug',
  path: '/crops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/lab': typeof LabRoute
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRoutesByTo {
  '/lab': typeof LabRoute
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/lab': typeof LabRoute
  '/crops/$slug': typeof CropsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/lab' | '/crops/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/lab' | '/crops/$slug'
  id: '__root__' | '/lab' | '/crops/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LabRoute: typeof LabRoute
  CropsSlugRoute: typeof CropsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$slug': {
      id: '/crops/$slug'
      path: '/crops/$slug'
      fullPath: '/crops/$slug'
      preLoaderRoute: typeof CropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LabRoute: LabRoute,
  CropsSlugRoute: CropsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
