/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropsIndexRouteImport } from './routes/crops.index'
import { Route as CropsSlugRouteImport } from './routes/crops.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsIndexRoute = CropsIndexRouteImport.update({
  id: '/crops/',
  path: '/crops/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsSlugRoute = CropsSlugRouteImport.update({
  id: '/crops/$slug',
  path: '/crops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crops/$slug': typeof CropsSlugRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crops/$slug': typeof CropsSlugRoute
  '/crops': typeof CropsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crops/$slug': typeof CropsSlugRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crops/$slug' | '/crops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crops/$slug' | '/crops'
  id: '__root__' | '/' | '/crops/$slug' | '/crops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropsSlugRoute: typeof CropsSlugRoute
  CropsIndexRoute: typeof CropsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/': {
      id: '/crops/'
      path: '/crops'
      fullPath: '/crops/'
      preLoaderRoute: typeof CropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$slug': {
      id: '/crops/$slug'
      path: '/crops/$slug'
      fullPath: '/crops/$slug'
      preLoaderRoute: typeof CropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropsSlugRoute: CropsSlugRoute,
  CropsIndexRoute: CropsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
